import { z } from "zod";

const auditActionSchema = z.enum([
	"campus_created",
	"campus_updated",
	"campus_activated",
	"campus_deactivated",
	"invitation_created",
	"invitation_revoked",
	"invitation_claimed",
	"member_role_changed",
	"member_access_changed",
	"member_removed",
	"payment_created",
	"payment_reversed",
	"refund_created",
	"enrollment_renewed",
	"enrollment_transferred",
	"lesson_completed",
	"schedule_rule_created",
	"schedule_rule_updated",
	"schedule_rule_deactivated",
	"schedule_rule_deleted",
	"lessons_generated",
	"lessons_bulk_rescheduled",
	"lessons_bulk_cancelled",
	"teacher_binding_changed",
	"class_paused",
	"class_resumed",
	"classroom_created",
	"classroom_updated",
	"classroom_activated",
	"classroom_deactivated",
	"makeup_lesson_created",
	"makeup_lesson_cancelled",
	"makeup_lesson_needs_reschedule",
	"enrollment_created",
	"enrollment_frozen",
	"enrollment_resumed",
	"enrollment_class_transferred",
	"enrollment_class_withdrawn",
	"student_merged",
	"lead_imported",
	"lead_exported",
	"notification_read",
	"notifications_marked_read",
	"manual_invoice_created",
	"invoice_adjusted",
	"refund_request_submitted",
	"refund_request_approved",
	"refund_request_rejected",
	"refund_request_cancelled",
	"arrears_status_changed",
	"receipt_generated",
	"receipt_voided",
	"receipt_reissued",
	"operation_task_created",
	"operation_task_updated",
	"operation_task_claimed",
	"operation_task_completed",
	"operation_task_reopened",
	"operation_task_cancelled",
	"student_imported",
	"student_exported",
	"students_bulk_updated",
	"analytics_filter_saved",
	"analytics_filter_updated",
	"analytics_filter_deleted",
	"analytics_exported",
]);

export const auditEventListInputSchema = z.object({
	action: auditActionSchema.optional(),
	actorUserId: z.string().optional(),
	createdAtFrom: z.iso.datetime({ offset: true }).optional(),
	createdAtTo: z.iso.datetime({ offset: true }).optional(),
	cursor: z.string().min(1).max(256).optional(),
	pageSize: z.number().int().min(1).max(100).default(50),
});
export const auditEventListResultSchema = z.object({
	items: z.array(
		z.object({
			id: z.uuid(),
			action: auditActionSchema,
			entityType: z.string(),
			entityId: z.uuid(),
			campusId: z.uuid().nullable(),
			actorUserId: z.string().nullable(),
			actorName: z.string().nullable(),
			createdAt: z.iso.datetime({ offset: true }),
		}),
	),
	nextCursor: z.string().nullable(),
});
export type AuditEventListInput = z.infer<typeof auditEventListInputSchema>;
export type AuditEventListResult = z.infer<typeof auditEventListResultSchema>;
